import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          "next": "Next",
          "skip": "Skip",
          "get_started": "Lets\nGet Started",
          "hey": "Hey ,",
          "super_fast_delivery":
              "Get Super Fast Delivery\nin Your First Hello !",
          "Log in": "Log in",
          "Login": "Login",
          "Enter Email": "Enter Email",
          "Enter Password": "Enter Password",
          "Password": "Password",
          "Forgot Password ?": "Forgot Password ?",
          "Forgot Password": "Forgot Password",
          "Enter the email address":
              "Enter the email address\nassociated with your account .",
          "Send": "Send",
          "Verification": "Verification",
          "Enter the verification code":
              "Enter the verification code we\nhave just sent you on your\nemail address",
          "Complete": "Complete",
          "Profile ": "Profile",
          "Total Deliveries": "Total Deliveries",
          "Today Deliveries": "Today Deliveries",
          "Cash In Hand": "Cash In Hand",
          "Borrowed Cash": "Borrowed Cash",
          "Driver Group": "Driver Group",
          "Notification": "Notification",
          "Dashboard": "Dashboard",
          "Hey,": "Hey,",
          "Total Distance": "Total\nDistance",
          "Total Deliveries Dash": "Total\nDeliveries",

          "Total Collection": "Total\nCollection",
          "Today Collection": "Today\nCollection",
          // "Today Deliveries": "Today\nDeliveries",
          "monthly Report Chart": "monthly Report Chart",
          "Fix Salary": "Fix Salary",
          "Month order": " Month order",
          "Target Reach": "Target Reach",
          "Total Order": "Total Order",
          "Deliveries": "Deliveries",
          "Upload": "Upload",
          "History": "History",
          "Home": "Home",
          "Logout": "Logout",
          "Upload Image": "Upload Image",
          "Please  Upload your Screen":
              "Please  Upload your Screen shot here .",
          "BROWSE FILES": "BROWSE FILES",
          "Confirm the daily submitting": "Confirm the daily submitting",
          "Confirm field": "Confirm field",
          "Transfer Money": "Transfer Money",
          "Supervisors Name ": "Supervisors Name ",
          "In Hand Money": "In Hand Money",
          "Borrow Money": "Borrow Money",
          "Limit": "Limit",
          "Total Money Transfer": "Total Money Transfer",
          "Transfer Now": "Transfer Now",
          "Cancel": "Cancel",
          "Your Transaction is completed":
              "Your Transaction is\ncompleted successfully",
          "Go to Dashboard": "Go to Dashboard",
          "Your Transection is not":
              "Your Transection is not\n completed successfully",
          "Vehicle Maintenance ": "Vehicle Maintenance ",
          "Repair & Replacement": "Repair & Replacement",
          "Maintenance": "Maintenance",
          "Wheeles & Tires": "Wheeles & Tires",
          "Other": "Other",
          "Message": "Message",
          "Screenshot of vehicle meter": "Screenshot of vehicle meter",
          "Today’s Delivery list": "Today’s Delivery list",
          "Select Date": "Select Date",
          "Success": "Success",
          "Email is Reuqired": "Email is Reuqired",
          "Password is Required": "Password is Required",
          "Finished at ": "Finished at ",

          //////////// supervisor en/////////////////
        },

        //Arabic LANGUAGE////////////
        'ar_SA': {
          "next": "مقبل",
          "skip": "تخطي",
          "get_started": "هيا بنا نبدأ",
          "hey": "يا هذا",
          "super_fast_delivery": "احصل على توصيل فائق السرعة\nفي أول ترحيب لك!",
          "Log in": "تسجيل الدخول",
          "Login": "تسجيل الدخول",
          "Enter Email": "أدخل البريد الإلكتروني",
          "Password": "شعار",
          "Forgot Password ?": "نسيت كلمة المرور ؟",
          "Forgot Password": "نسيت كلمة المرور",
          "Enter the email address":
              "أدخل عنوان البريد الإلكتروني\nالمرتبطة بحسابك .",
          "Send": "ارسل",
          "Verification": "التحقق",
          "Enter the verification code":
              "أدخل رمز التحقق\nلقد أرسلت لك للتو على\nعنوان البريد الإلكتروني",
          "Complete": "كامل",
          "Profile ": "ملف تعريف",
          "Total Deliveries": "إجمالي عمليات التسليم",
          "Today Deliveries": "تسليم اليوم",
          "Cash In Hand": "النقود في متناول اليد",
          "Borrowed Cash": "النقد المقترض",
          "Driver Group": "مجموعة السائقين",
          "Notification": "اخطار",
          "Dashboard": "لوحه القياده",
          "Hey,": "يا هذا",
          "Total Distance": "مجموع\nبون",
          "Total Deliveries Dash": "مجموع\nتسليم",
          "Total Collection": "مجموع\nمجموعة",
          "monthly Report Chart": "مخطط التقرير الشهري",
          "Fix Salary": "إصلاح الراتب",
          "Month order": " طلب الشهر",
          "Target Reach": "الوصول المستهدف",
          "Total Order": "إجمالي الطلب",
          "Deliveries": "تسليم",
          "Upload": "رفع",
          "History": "تاريخ",
          "Home": "وطن",
          "Logout": "الخروج",
          "Upload Image": "تحميل الصورة",
          "Please  Upload your Screen": "يرجى تحميل لقطة الشاشة الخاصة بك هنا.",
          "BROWSE FILES": "تصفح الملفات",
          "Confirm the daily submitting": "تأكيد الإرسال اليومي",
          "Confirm field": "حقل التأكيد",
          "Transfer Money": "تحويل الأموال",
          "Supervisors Name ": "اسم المشرفين ",
          "In Hand Money": "في متناول اليد",
          "Borrow Money": "اقتراض المال",
          "Limit": "حد",
          "Total Money Transfer": "إجمالي تحويل الأموال",
          "Transfer Now": "نقل الآن",
          "Cancel": "إلغاء الأمر",
          "Your Transaction is completed": "معاملتك هي\nاكتمل بنجاح",
          "Go to Dashboard": "انتقل إلى لوحة التحكم",
          "Your Transaction is not": "معاملتك ليست كذلك\n اكتمل بنجاح",
          "Vehicle Maintenance ": "صيانة المركبات ",
          "Repair & Replacement": "إصلاح واستبدال",
          "Maintenance": "صيانة",
          "Wheeles & Tires": "العجلات والإطارات",
          "Other": "آخر",
          "Message": "رسالة",
          "Screenshot of vehicle meter": "لقطة شاشة لعداد السيارة",
          "Today’s Delivery list": "قائمة التوصيل اليوم",
          "Select Date": "اختر التاريخ",
          "Success": "نجاح",
          "Email is Reuqired": "البريد الإلكتروني مطلوب",
          "Password is Required": "كلمة المرور مطلوبة",
          "Enter Password": "أدخل كلمة المرور",
          "Finished at ": " انتهى في",

          //////////// supervisor ar/////////////////
        },
      };
}
